version: '3'

services:
  app:
    build:
      context: node
    networks:
      node-network:
        aliases: 
          - app
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    depends_on: 
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s node index.js
    image: challenge02-fullcycle-node

  nginx:
    build:
      context: nginx
    networks: 
      - node-network
    tty: true
    container_name: nginx
    ports:
      - "8080:80"
    image: challenge02-fullcycle-nginx
    depends_on: 
      - app
    entrypoint: dockerize -wait tcp://app:3000/health -timeout 120s nginx
    command: -g "daemon off;"

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge